create or replace function public.product_expiry_status(p_expiry_date date) returns public.expiry_status language sql stable set search_path=public,extensions as $$ select case when p_expiry_date is null then 'NORMAL'::public.expiry_status when p_expiry_date < current_date then 'EXPIRED'::public.expiry_status when p_expiry_date <= current_date + 30 then 'EXPIRING_SOON'::public.expiry_status else 'NORMAL'::public.expiry_status end $$;
create or replace function public.is_expiring_soon(p_expiry_date date) returns boolean language sql stable set search_path=public,extensions as $$ select public.product_expiry_status(p_expiry_date)='EXPIRING_SOON' $$;
revoke execute on function public.handle_new_user() from anon, authenticated;
revoke execute on function public.product_expiry_status(date) from anon, authenticated;
revoke execute on function public.is_expiring_soon(date) from anon, authenticated;

create policy user_roles_self_read on public.user_roles for select using (user_id=auth.uid());
create policy sellers_owner_read on public.sellers for select using (user_id=auth.uid());
create policy shops_owner_read on public.shops for select using (exists(select 1 from public.sellers s where s.id=seller_id and s.user_id=auth.uid()));
create policy shops_owner_update on public.shops for update using (exists(select 1 from public.sellers s where s.id=seller_id and s.user_id=auth.uid())) with check (exists(select 1 from public.sellers s where s.id=seller_id and s.user_id=auth.uid()));
create policy products_owner_read on public.products for select using (exists(select 1 from public.shops sh join public.sellers s on s.id=sh.seller_id where sh.id=shop_id and s.user_id=auth.uid()));
create policy products_owner_insert on public.products for insert with check (exists(select 1 from public.shops sh join public.sellers s on s.id=sh.seller_id where sh.id=shop_id and s.user_id=auth.uid()));
create policy products_owner_update on public.products for update using (exists(select 1 from public.shops sh join public.sellers s on s.id=sh.seller_id where sh.id=shop_id and s.user_id=auth.uid())) with check (exists(select 1 from public.shops sh join public.sellers s on s.id=sh.seller_id where sh.id=shop_id and s.user_id=auth.uid()));
create policy inventory_owner_read on public.inventory for select using (exists(select 1 from public.products p join public.shops sh on sh.id=p.shop_id join public.sellers s on s.id=sh.seller_id where p.id=product_id and s.user_id=auth.uid()));
create policy inventory_owner_update on public.inventory for update using (exists(select 1 from public.products p join public.shops sh on sh.id=p.shop_id join public.sellers s on s.id=sh.seller_id where p.id=product_id and s.user_id=auth.uid()));
create policy inventory_movements_owner_read on public.inventory_movements for select using (exists(select 1 from public.products p join public.shops sh on sh.id=p.shop_id join public.sellers s on s.id=sh.seller_id where p.id=product_id and s.user_id=auth.uid()));
create policy delivery_assignments_courier_read on public.delivery_assignments for select using (courier_id=auth.uid());
create policy courier_locations_courier_insert on public.courier_locations for insert with check (courier_id=auth.uid());
create policy courier_locations_courier_read on public.courier_locations for select using (courier_id=auth.uid());
create policy order_groups_customer_read on public.order_groups for select using (exists(select 1 from public.orders o where o.id=order_id and o.customer_id=auth.uid()));
create policy order_groups_seller_read on public.order_groups for select using (exists(select 1 from public.shops sh join public.sellers s on s.id=sh.seller_id where sh.id=shop_id and s.user_id=auth.uid()));
create policy order_items_customer_read on public.order_items for select using (exists(select 1 from public.order_groups og join public.orders o on o.id=og.order_id where og.id=order_group_id and o.customer_id=auth.uid()));
create policy order_items_seller_read on public.order_items for select using (exists(select 1 from public.order_groups og join public.shops sh on sh.id=og.shop_id join public.sellers s on s.id=sh.seller_id where og.id=order_group_id and s.user_id=auth.uid()));
create policy order_packages_customer_read on public.order_packages for select using (exists(select 1 from public.order_groups og join public.orders o on o.id=og.order_id where og.id=order_group_id and o.customer_id=auth.uid()));
create policy order_packages_seller_read on public.order_packages for select using (exists(select 1 from public.order_groups og join public.shops sh on sh.id=og.shop_id join public.sellers s on s.id=sh.seller_id where og.id=order_group_id and s.user_id=auth.uid()));
create policy payments_customer_read on public.payments for select using (exists(select 1 from public.orders o where o.id=order_id and o.customer_id=auth.uid()));
create policy conversation_members_self_insert on public.conversation_members for insert with check (user_id=auth.uid());
create policy reviews_owner_read on public.reviews for select using (customer_id=auth.uid());
create policy reviews_owner_update on public.reviews for update using (customer_id=auth.uid()) with check (customer_id=auth.uid());