create extension if not exists pgcrypto;
create extension if not exists citext;
create extension if not exists pg_trgm;
create extension if not exists postgis;
create extension if not exists vector;

create type public.user_role as enum ('CUSTOMER','SELLER','RESTAURANT','COURIER','SERVICE_PROVIDER','MECHANIC','TRANSPORT_COMPANY','DRIVER','SUPPORT','MODERATOR','FINANCE','LOGISTICS_ADMIN','ADMIN','SUPER_ADMIN');
create type public.account_status as enum ('ACTIVE','SUSPENDED','BLOCKED');
create type public.shop_status as enum ('DRAFT','PENDING_REVIEW','ACTIVE','SUSPENDED','CLOSED');
create type public.verification_status as enum ('UNVERIFIED','PENDING','VERIFIED','REJECTED');
create type public.product_status as enum ('DRAFT','PENDING_REVIEW','ACTIVE','INACTIVE','REJECTED','ARCHIVED');
create type public.order_status as enum ('PENDING_PAYMENT','PAID','CONFIRMED','PREPARING','READY_FOR_PICKUP','PARTIALLY_FULFILLED','IN_TRANSIT','DELIVERED','CANCELLED','REFUNDED','DISPUTED');
create type public.payment_status as enum ('PENDING','PROCESSING','SUCCEEDED','FAILED','CANCELLED','REFUNDED','PARTIALLY_REFUNDED');
create type public.delivery_status as enum ('CREATED','READY_FOR_PICKUP','ASSIGNED','PICKED_UP','IN_TRANSIT','DELIVERED','RETURNED','DAMAGED','LOST','CANCELLED');
create type public.message_status as enum ('SENT','DELIVERED','READ');
create type public.review_status as enum ('PENDING','PUBLISHED','HIDDEN','REPORTED');
create type public.expiry_status as enum ('NORMAL','EXPIRING_SOON','EXPIRED');

create table public.profiles (id uuid primary key references auth.users(id) on delete cascade, first_name text, last_name text, display_name text, phone text, avatar_url text, status public.account_status not null default 'ACTIVE', verification_status public.verification_status not null default 'UNVERIFIED', created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.user_roles (user_id uuid not null references public.profiles(id) on delete cascade, role public.user_role not null, created_at timestamptz not null default now(), primary key (user_id,role));
create table public.sellers (id uuid primary key default gen_random_uuid(), user_id uuid not null unique references public.profiles(id) on delete restrict, verification_status public.verification_status not null default 'PENDING', business_name text, business_phone text, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.shops (id uuid primary key default gen_random_uuid(), seller_id uuid not null references public.sellers(id) on delete restrict, name text not null, normalized_name text not null unique, logo_url text, cover_url text, description text, phone text, address text, location geography(point,4326), status public.shop_status not null default 'DRAFT', verification_status public.verification_status not null default 'PENDING', created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.category_types (id uuid primary key default gen_random_uuid(), name text not null unique, slug text not null unique, is_active boolean not null default true, sort_order integer not null default 0, created_at timestamptz not null default now());
create table public.categories (id uuid primary key default gen_random_uuid(), category_type_id uuid references public.category_types(id) on delete set null, parent_id uuid references public.categories(id) on delete set null, name text not null, slug text not null unique, icon_url text, image_url text, is_active boolean not null default true, sort_order integer not null default 0, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.products (id uuid primary key default gen_random_uuid(), shop_id uuid not null references public.shops(id) on delete restrict, category_id uuid references public.categories(id) on delete set null, name text not null, slug text not null unique, description text, sku text, price numeric(14,2) not null check(price>=0), compare_at_price numeric(14,2) check(compare_at_price is null or compare_at_price>=0), status public.product_status not null default 'DRAFT', is_expirable boolean not null default false, expiry_date date, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), check(not is_expirable or expiry_date is not null));
create table public.product_variants (id uuid primary key default gen_random_uuid(), product_id uuid not null references public.products(id) on delete cascade, name text not null, sku text, price numeric(14,2) check(price is null or price>=0), attributes jsonb not null default '{}'::jsonb, created_at timestamptz not null default now());
create table public.product_images (id uuid primary key default gen_random_uuid(), product_id uuid not null references public.products(id) on delete cascade, storage_path text not null, sort_order integer not null default 0, alt_text text, created_at timestamptz not null default now());
create table public.inventory (product_id uuid primary key references public.products(id) on delete cascade, quantity integer not null default 0 check(quantity>=0), reserved_quantity integer not null default 0 check(reserved_quantity>=0), updated_at timestamptz not null default now(), check(reserved_quantity<=quantity));
create table public.inventory_movements (id uuid primary key default gen_random_uuid(), product_id uuid not null references public.products(id) on delete restrict, quantity_delta integer not null, reason text not null, reference_id uuid, created_by uuid references public.profiles(id) on delete set null, created_at timestamptz not null default now());
create table public.carts (id uuid primary key default gen_random_uuid(), customer_id uuid not null references public.profiles(id) on delete cascade, status text not null default 'ACTIVE' check(status in ('ACTIVE','CHECKED_OUT','ABANDONED')), created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.cart_items (id uuid primary key default gen_random_uuid(), cart_id uuid not null references public.carts(id) on delete cascade, product_id uuid not null references public.products(id) on delete restrict, variant_id uuid references public.product_variants(id) on delete restrict, quantity integer not null check(quantity>0), unit_price numeric(14,2) not null check(unit_price>=0), created_at timestamptz not null default now());
create unique index uq_cart_product_variant on public.cart_items(cart_id,product_id,coalesce(variant_id,'00000000-0000-0000-0000-000000000000'::uuid));
create table public.orders (id uuid primary key default gen_random_uuid(), customer_id uuid not null references public.profiles(id) on delete restrict, status public.order_status not null default 'PENDING_PAYMENT', subtotal numeric(14,2) not null default 0 check(subtotal>=0), delivery_fee numeric(14,2) not null default 0 check(delivery_fee>=0), discount_total numeric(14,2) not null default 0 check(discount_total>=0), total numeric(14,2) not null default 0 check(total>=0), currency char(3) not null default 'XOF', delivery_address jsonb, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.order_groups (id uuid primary key default gen_random_uuid(), order_id uuid not null references public.orders(id) on delete cascade, shop_id uuid not null references public.shops(id) on delete restrict, status public.order_status not null default 'PAID', subtotal numeric(14,2) not null default 0 check(subtotal>=0), created_at timestamptz not null default now());
create table public.order_items (id uuid primary key default gen_random_uuid(), order_group_id uuid not null references public.order_groups(id) on delete cascade, product_id uuid not null references public.products(id) on delete restrict, variant_id uuid references public.product_variants(id) on delete restrict, product_name text not null, quantity integer not null check(quantity>0), unit_price numeric(14,2) not null check(unit_price>=0), total_price numeric(14,2) not null check(total_price>=0), created_at timestamptz not null default now());
create table public.order_packages (id uuid primary key default gen_random_uuid(), order_group_id uuid not null references public.order_groups(id) on delete cascade, status public.delivery_status not null default 'CREATED', weight_kg numeric(10,3), volume_m3 numeric(12,6), pickup_code_hash text, picked_up_at timestamptz, delivered_at timestamptz, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.payments (id uuid primary key default gen_random_uuid(), order_id uuid not null references public.orders(id) on delete restrict, provider text not null, provider_reference text, amount numeric(14,2) not null check(amount>=0), currency char(3) not null default 'XOF', status public.payment_status not null default 'PENDING', metadata jsonb not null default '{}'::jsonb, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(provider,provider_reference));
create table public.delivery_assignments (id uuid primary key default gen_random_uuid(), package_id uuid not null references public.order_packages(id) on delete cascade, courier_id uuid not null references public.profiles(id) on delete restrict, status public.delivery_status not null default 'ASSIGNED', assigned_at timestamptz not null default now(), accepted_at timestamptz, completed_at timestamptz);
create table public.courier_locations (id bigint generated always as identity primary key, courier_id uuid not null references public.profiles(id) on delete cascade, location geography(point,4326) not null, accuracy_m numeric, recorded_at timestamptz not null default now());
create table public.conversations (id uuid primary key default gen_random_uuid(), order_id uuid references public.orders(id) on delete set null, type text not null default 'GENERAL' check(type in ('GENERAL','ORDER','SUPPORT','ADMINISTRATION')), created_at timestamptz not null default now());
create table public.conversation_members (conversation_id uuid not null references public.conversations(id) on delete cascade, user_id uuid not null references public.profiles(id) on delete cascade, joined_at timestamptz not null default now(), primary key(conversation_id,user_id));
create table public.messages (id uuid primary key default gen_random_uuid(), conversation_id uuid not null references public.conversations(id) on delete cascade, sender_id uuid not null references public.profiles(id) on delete restrict, body text, attachment_path text, status public.message_status not null default 'SENT', created_at timestamptz not null default now(), check(coalesce(length(body),0)>0 or attachment_path is not null));
create table public.reviews (id uuid primary key default gen_random_uuid(), customer_id uuid not null references public.profiles(id) on delete restrict, product_id uuid references public.products(id) on delete set null, shop_id uuid references public.shops(id) on delete set null, rating smallint not null check(rating between 1 and 5), body text, status public.review_status not null default 'PENDING', created_at timestamptz not null default now());
create table public.audit_logs (id bigint generated always as identity primary key, actor_id uuid references public.profiles(id) on delete set null, action text not null, entity_type text not null, entity_id uuid, metadata jsonb not null default '{}'::jsonb, created_at timestamptz not null default now());

create index idx_categories_type_sort on public.categories(category_type_id,is_active,sort_order);
create index idx_products_shop_status on public.products(shop_id,status);
create index idx_products_category_status on public.products(category_id,status);
create index idx_products_expiry on public.products(expiry_date) where is_expirable=true;
create index idx_orders_customer_created on public.orders(customer_id,created_at desc);
create index idx_order_groups_shop on public.order_groups(shop_id);
create index idx_packages_status on public.order_packages(status);
create index idx_delivery_assignments_courier on public.delivery_assignments(courier_id,status);
create index idx_courier_locations_time on public.courier_locations(courier_id,recorded_at desc);
create index idx_messages_conversation_time on public.messages(conversation_id,created_at desc);
create index idx_reviews_shop on public.reviews(shop_id,status);
create index idx_shops_location on public.shops using gist(location);
create index idx_courier_locations_geo on public.courier_locations using gist(location);
create index idx_products_name_trgm on public.products using gin(name gin_trgm_ops);
create index idx_shops_name_trgm on public.shops using gin(name gin_trgm_ops);

alter table public.profiles enable row level security;
alter table public.user_roles enable row level security;
alter table public.sellers enable row level security;
alter table public.shops enable row level security;
alter table public.category_types enable row level security;
alter table public.categories enable row level security;
alter table public.products enable row level security;
alter table public.product_variants enable row level security;
alter table public.product_images enable row level security;
alter table public.inventory enable row level security;
alter table public.inventory_movements enable row level security;
alter table public.carts enable row level security;
alter table public.cart_items enable row level security;
alter table public.orders enable row level security;
alter table public.order_groups enable row level security;
alter table public.order_items enable row level security;
alter table public.order_packages enable row level security;
alter table public.payments enable row level security;
alter table public.delivery_assignments enable row level security;
alter table public.courier_locations enable row level security;
alter table public.conversations enable row level security;
alter table public.conversation_members enable row level security;
alter table public.messages enable row level security;
alter table public.reviews enable row level security;
alter table public.audit_logs enable row level security;